version: "3.8"
# TODO: figure out exporting logs
# TODO: figure out what needs to be changed for a dev profile and production. Might need different docker-compose files
services:
  api-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${API_POSTGRES_USER}
      - POSTGRES_PASSWORD=${API_POSTGRES_PASSWORD}
      - POSTGRES_DB=defense_drill
    env_file:
      - defense_drill.env
    volumes:
      - api-database-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  security-database:
    image: postgres
    ports:
      - "9998:5432"
    environment:
      - POSTGRES_USER=${SECURITY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SECURITY_POSTGRES_PASSWORD}
      - POSTGRES_DB=security
    env_file:
      - defense_drill.env
    volumes:
      - security-database-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  vault:
    # TODO: figure out the --cap-add=IPC_LOCK passed in during docker run?
    image: hashicorp/vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    env_file:
      - defense_drill.env
    # TODO: for prod, need to bring in a .hcl config file and copy to container
    volumes:
      - vault-volume:/vault/data # TODO: check this in prod
    # healthcheck:
      # TODO: Figure this ^^ out

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  # REST_API_DB_URL=jdbc:postgresql://api-database:5432/defense_drill
  # SECURITY_API_DB_URL=jdbc:postgresql://security-database:5432/security

volumes:
  api-database-volume:
  security-database-volume:
  vault-volume:
