version: "3.8"
# TODO: figure out exporting logs
services:
  api-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${API_POSTGRES_USER}
      - POSTGRES_PASSWORD=${API_POSTGRES_PASSWORD}
      - POSTGRES_DB=defense_drill
    env_file:
      - defense_drill.env
    volumes:
      - api-database-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  api-database-volume: